server:
  port: ${PORT:8080}

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: agenda-service
          uri: lb://agenda
          predicates:
            - Path=/api/agenda/**

        - id: disponibilidad-service
          uri: lb://disponibilidadProfesional
          predicates:
            - Path=/api/disponibilidad/**

        - id: cliente-service
          uri: lb://cliente
          predicates:
            - Path=/api/cliente/**

        - id: profesional-service
          uri: lb://profesional
          predicates:
            - Path=/api/profesional/**

        - id: tipo-servicio-service
          uri: lb://tipoServicio
          predicates:
            - Path=/api/tipoServicio/**

        - id: agenda-swagger
          uri: lb://agenda
          predicates:
            - Path=/agenda/v3/api-docs

        - id: cliente-swagger
          uri: lb://cliente
          predicates:
            - Path=/cliente/v3/api-docs

        - id: disponibilidad-swagger
          uri: lb://disponibilidadProfesional
          predicates:
            - Path=/disponibilidadProfesional/v3/api-docs

        - id: profesional-swagger
          uri: lb://profesional
          predicates:
            - Path=/profesional/v3/api-docs

        - id: tipo-servicio-swagger
          uri: lb://tipoServicio
          predicates:
            - Path=/tipoServicio/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"